### ISSUE TITLE
Did not get status code 200

### ISSUE THREAD

**Issue by anoop2503** [RobustPerception/azure_metrics_exporter#104]
Hi,

I am trying to set up the exporter as a kubernetes application and using configmap for creating configuration file. However, when I am deploying the application I am getting an following error.

`Failed to get token: Did not get status code 200, got: 404 with body:`

Here is the configmap I created for the configuration.
```
apiVersion: v1
data:
  azure.yml: |
    active_directory_authority_url: "https://login.microsoftonline.com/"
    resource_manager_url: "https://management.azure.com/"
    credentials:
      client_id: "4xxxxxxx-4xxx-4xxx-8xxx-2xxxxxxxxxxx"
    resource_groups:
      - resource_group: "my_resource_group_name"
        resource_types:
          - "Microsoft.Compute/virtualMachines"
        metrics:
          - name: "Disk Read Bytes"
          - name: "Disk Write Bytes"
kind: ConfigMap
metadata:
  name: azure-exporter
```

Any suggestions?
