### ISSUE TITLE
Gaps in data scraped from Azure Monitor

### ISSUE THREAD

**Issue by anoop2503** [RobustPerception/azure_metrics_exporter#112]
Hi,

I am trying to scrape Virtual Machine metrics from Azure monitor using this exporter. But I can see a lot of gaps in the graph. I am running the exporter in kubernetes environment and using the metric "percentage_cpu_percent_average" to plot the graph in Grafana/Prometheus. Please find my exporter configuration below.

```
   active_directory_authority_url: "https://login.microsoftonline.com/"
    resource_manager_url: "https://management.azure.com/"
    credentials:
      subscription_id: ******-****-******-*****-******
    resource_groups:
      - resource_group: "***********"
        resource_types:
          - "Microsoft.Compute/virtualMachines"
        metrics:
          - name: "Percentage CPU"
          - name: "Available Memory Bytes"
          - name: "Network In Total"
          - name: "Network Out Total"
          - name: "Disk Read Bytes"
          - name: "Disk Write Bytes"
          - name: "Disk Read Operations/Sec"
          - name: "Disk Write Operations/Sec"
          - name: "Inbound Flows"
          - name: "Outbound Flows"
```

The prometheus is scraping metrics from the exporter in every 30 seconds and I believe there is no scrape interval configuration required for the exporter itself to scrape metrics from Azure Monitor. 

The data is matching to the actual data in Azure monitor data. However, there is no gap if we directly check the Azure Monitor dashboards. Please share the details, if anyone has any idea why I am seeing the gaps in the data received from exporter?

Thank You,
