### ISSUE TITLE
Set metric namespace?

### ISSUE THREAD

**Issue by carlpett** [RobustPerception/azure_metrics_exporter#25]
Right now the metric names are a bit all over the place, since we just take what we get from Azure and use that as the name.
Could we set the namespace to `azure`? This would be a breaking change of course. As a motivation, the current approach seems to hurt discoverability of the metrics in my environment at least, since the majority of exporters/applications do some prefixing out their names. People _could_ first query for `{job="azure-metrics"}` and see what is available, but from what I've seen this doesn't happen.

**Comment by brian-brazil** [comment]
I see discoverability as a tooling problem downstream, as with most applications they would not share a common prefix (think `process_`). A breaking change to workaround this in one exporter doesn't feel right to me.

**Comment by carlpett** [comment]
Yeah, agreed in principle. That downstream tooling isn't available anywhere, though (as far as I know neither Prometheus UI nor Grafana has it), so thus the proposal.
I'm fine with just doing some relabeling for prefixing, though, if this is just an issue for the teams I work with, rather than a common thing. Here, however, inexperienced Prometheus users find it confusing.

**Comment by adam-resdiary** [comment]
@brian-brazil what about adding a flag to the exporter so you could do something like:

```shell
./azure_metrics_exporter --metrics.prefix azure
```

And it would optionally prefix all the metrics with `azure_`. That way it wouldn't be a breaking change, but would allow people to set a prefix if they wanted.

Given the metric names are generated automatically, and some of them are a bit unintuitive anyway, I'm not convinced you're likely to be able to aggregate them with metrics from another exporter anyway (because the metric names are pretty unlikely to match exactly).

For example `cpu_percent_percent_average` gives you the Average CPU percentage for an SQL Server database (amongst other resources). It makes sense that the same metric name should be consistent within the Azure exporter, but it doesn't seem likely to me that other exporters would happen to choose `cpu_percent_percent_average` as a name, making me think that `azure_cpu_percent_percent_average` would work just as well.

Just a thought 😄

**Comment by brian-brazil** [comment]
Metric names are not something that should be configurable by an operator.

**Comment by sepich** [comment]
+1 for this, for now have to do:
```
    metric_relabel_configs:
      - source_labels: [__name__]
        replacement: azure_${1}
        target_label: __name__
```
But it works because only Azure metrics are returned. If/when exporter would start to return `go` or own `process` metrics - mess would arrive!

**Comment by medmedchiheb** [comment]
```
        metric_relabel_configs:
          - source_labels: [kubernetes_name]
            regex: '^azure-metrics-exporter$'
            replacement: azure_${1}
            target_label: __name__
```

i did this, but does not work,

the metric name are gone
![image](https://user-images.githubusercontent.com/15221272/70513306-a5f70c00-1b31-11ea-99c1-e2787770f0d6.png)
