### ISSUE TITLE
Error "Unable to query metrics API"

### ISSUE THREAD

**Issue by rca0** [RobustPerception/azure_metrics_exporter#52]
I have this configuration:

**azure.yml**
```
credentials:
  subscription_id: <secret>
  tenant_id: <secret>
  client_id: <secret>
  client_secret: <secret>

targets:
  - resource: "/resourceGroups/<resource_group>/providers/Microsoft.Compute/virtualMachines/<machine_name>"
    metrics:
    - name: "Percentage CPU"
    - name: "Network In"
    - name: "Network Out"
"/resourceGroups/<resource_group>/providers/Microsoft.Compute/virtualMachines/<machine_name>"
    metrics:
    - name: "Http2xx"
    - name: "Http5xx"
```

When i attempt to get metrics i got this output:

`$ curl IP_ADDRESS:9276/metrics`
                               
```

# HELP network_in_bytes_average network_in_bytes_average
# TYPE network_in_bytes_average gauge
network_in_bytes_average{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP network_in_bytes_max network_in_bytes_max
# TYPE network_in_bytes_max gauge
network_in_bytes_max{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP network_in_bytes_min network_in_bytes_min
# TYPE network_in_bytes_min gauge
network_in_bytes_min{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP network_in_bytes_total network_in_bytes_total
# TYPE network_in_bytes_total gauge
network_in_bytes_total{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP network_out_bytes_average network_out_bytes_average
# TYPE network_out_bytes_average gauge
network_out_bytes_average{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP network_out_bytes_max network_out_bytes_max
# TYPE network_out_bytes_max gauge
network_out_bytes_max{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP network_out_bytes_min network_out_bytes_min
# TYPE network_out_bytes_min gauge
network_out_bytes_min{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP network_out_bytes_total network_out_bytes_total
# TYPE network_out_bytes_total gauge
network_out_bytes_total{resource_group="<resource_group>",resource_name="<machine_name>"} 0
# HELP percentage_cpu_percent_average percentage_cpu_percent_average
# TYPE percentage_cpu_percent_average gauge
percentage_cpu_percent_average{resource_group="<resource_group>",resource_name="<machine_name>"} 6.2375
# HELP percentage_cpu_percent_max percentage_cpu_percent_max
# TYPE percentage_cpu_percent_max gauge
percentage_cpu_percent_max{resource_group="<resource_group>",resource_name="<machine_name>"} 6.49
# HELP percentage_cpu_percent_min percentage_cpu_percent_min
# TYPE percentage_cpu_percent_min gauge
percentage_cpu_percent_min{resource_group="<resource_group>",resource_name="<machine_name>"} 6.09
# HELP percentage_cpu_percent_total percentage_cpu_percent_total
# TYPE percentage_cpu_percent_total gauge
percentage_cpu_percent_total{resource_group="<resource_group>",resource_name="<machine_name>"} 24.95
```

And i got this error from **azure-metrics-exporter**:

```
azure_metrics_exporter     --config.file /opt/azure-exporter/azure.yml --web.listen-address=":9276"
2019/04/05 13:45:53 azure_metrics_exporter listening on port :9276
2019/04/05 13:46:02 Failed to get metrics for target /resourceGroups/<resource_group>/providers/Microsoft.Compute/virtualMachines/<machine_name>: Unable to query metrics API with status code: 400
```

There is something wrong with my config file?
