### ISSUE TITLE
SQL Metrics not pulling in for server with multiple databases

### ISSUE THREAD

**Issue by andrewmitchell21** [RobustPerception/azure_metrics_exporter#62]
I can see a previous issue was raised for this under https://github.com/RobustPerception/azure_metrics_exporter/issues/40
and is marked as fixed, however, I appear to be getting the same issue.

I have the following config for example:

```
resource_groups:
  - resource_group: "test-rg"
    resource_types:
    - "Microsoft.Sql/servers/databases"
    metrics:
    - name: "dtu_used"
```

The above will only return scrapes for a single db and not all databases, also in the logs I am getting a 400 error for the all other databases on the same resource group
