### ISSUE TITLE
"no token found" error because of the naming conventions 

### ISSUE THREAD

**Issue by Arjoni** [RobustPerception/azure_metrics_exporter#7]
I am getting "no token found" error when I activate some metrics at azure.yml. It looks like this happens with metrics which name has a "/" like "Disk Read Operations/Sec" in the exporter config. Is this a bug in azure metrics exporter? 

```
---

credentials:
  subscription_id: xxxx
  client_id: xxxx
  client_secret: xxxx
  tenant_id: xxxx

targets:
  - resource: "/resourceGroups/myvm/providers/Microsoft.Compute/virtualMachines/myvmm/"
    metrics:
    - name: "Percentage CPU"
    - name: "Network In"
    - name: "Network Out"
    - name: "Disk Read Bytes"
    - name: "Disk Write Bytes"
#    - name: "Disk Read Operations/Sec"  **This doesn't work**
#    - name: "Disk Write Operations/Sec"   **This doesn't work**
    - name: "CPU Credits Remaining"
    - name: "CPU Credits Consumed"
#    - name: "Per Disk Read Bytes/sec"   **This doesn't work**
#    - name: "Per Disk Write Bytes/sec"  **This doesn't work**
#    - name: "Per Disk Read Operations/Sec"  **This doesn't work**
#    - name: "Per Disk Write Operations/Sec"   **This doesn't work**
    - name: "Per Disk QD"
#    - name: "OS Per Disk Read Bytes/sec"   **This doesn't work**
#    - name: "OS Per Disk Write Bytes/sec"   **This doesn't work**
#    - name: "OS Per Disk Read Operations/Sec"   **This doesn't work**
#    - name: "OS Per Disk Write Operations/Sec"   **This doesn't work**
    - name: "OS Per Disk QD"

```
