### ISSUE TITLE
Dimensions support for metrics

### ISSUE THREAD

**Issue by sujithms** [RobustPerception/azure_metrics_exporter#85]
Hi,

I am unable to add a dimension for Event hub namespace, say a particular event hub entity for the namespace. Is there a way to achieve this?

**Comment by gregoryfischer** [comment]
In both Datadog and in the Grafana Azure Datasource, ascertaining DocumentDB(CosmosDB) throttled requests, is done by checking the StatusCode dimension that should be returned by the TotalRequests metric of the Microsoft.DocumentDB/databaseAccounts metric namespace.

Again, this is returned by the Grafana datasource, but no metric dimensions are being returned with the azure_metrics_exporter.

Is this yet to be implemented or is this in the current documentation and I have not understood?

```
    targets:
      - resource: "/resourceGroups/MyResourceGroup/providers/Microsoft.DocumentDB/databaseAccounts/MyDatabase"
        metric_namespace: "Microsoft.DocumentDB/databaseAccounts"
        metrics:
        - name: AvailableStorage
        - name: DataUsage
        - name: DocumentCount
        - name: IndexUsage
        - name: MetadataRequests
        - name: ProvisionedThroughput
        - name: ReplicationLatency
        - name: TotalRequests
```
